app:
  telegram-token: test-token
  vk-token: test-token
  hse-client-id: app-x-android
  hse-redirect-uri: ru.hse.hseappx://saml.hse.ru/authorize_callback
  hse-login: test-login
  hse-password: test-password
  min-year: 2006
  max-year: 2008

spring:
  application:
    name: Unicef player finder
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/unicef
    username: postgres
    password: postgres

